name: 'SSH Remote Commands'
description: 'Executing remote ssh commands'
inputs:
  SSH_PRIVATE_KEY:
    description: 'ssh key'
    required: true
  port:
    description: 'ssh port'
    default: 22
  REMOTE_HOST:
    description: 'remote host'
    required: true
  username:
    description: 'ssh username'
  sync:
    description: 'synchronous execution if multiple hosts'
    default: false
  timeout:
    description: 'timeout for ssh to host'
    default: "30s"
  command_timeout:
    description: 'timeout for ssh command'
    default: "10m"
  fingerprint:
    description: 'sha256 fingerprint of the host public key'
  script:
    description: 'execute commands'
  script_stop:
    description: 'stop script after first failure'
    default: false
  envs:
    description: 'pass environment variable to shell script'
  debug:
    description: 'enable debug mode'
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  
branding:
  icon: 'terminal'
  color: 'gray-dark'
