KW_CALCULATION = 'calculation'
KW_ERROR = 'error'
KW_MODELNAME='modelname'

SCHEMA_REL_DIR = 'app/static/'

HTTP_DELETE='DELETE'
HTTP_GET='GET'
HTTP_POST='POST'
HTTP_PUT='PUT'

HTTP_OK = 200
HTTP_CREATED = 201
HTTP_NO_CONTENT = 204

HTTP_BAD_REQUEST = 400
HTTP_CONFLICT = 409
HTTP_NOT_FOUND = 404
HTTP_UNPROCESSABLE_ENTITY = 422

HTTP_INTERNAL_SERVER_ERROR = 500
