name: execute remote ssh to pull updates from master
on:
  push:
    branches:
      - master
      - dev
      - github_actions_new_workflow
  pull_request:
    branches: 
      - master
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: DeployServer
        uses: bpape1usa/SER401-Project43@github_actions_new_workflow
        with:
          debug: true
          REMOTE_HOST: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.GALILEO_DEPLOY }}
          port: ${{ secrets.PORT }}
          script: |
            export FLASK_RUN_HOST=0.0.0.0
            export FLASK_RUN_PORT=8010
            export FLASK_KEY=${{ secrets.FLASK_KEY }}
            export MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
            export MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            git clone git@github.com:bpape1usa/SER401-Project43.git
            git fetch origin -a
            git status 
            ls 
            docker-compose up --build --remove-orphans -d
