name: Create Docs and SSH into Server
on:
  push:
    branches:
      - master
      - dev
      - sprint10-lclindbe
  pull_request_target:
    branches:
      - dev
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: CreateDocs
        uses: ammaraskar/sphinx-action@0.4
        with:
          docs_folder: /Sphinx/source/
          pre-build-command: sphinx-apidoc -f -o ../Sphinx/source .
      - name: DeployServer
        uses:  appleboy/ssh-action@master
        with:
          host: galileo.sese.asu.edu
          username: t43-capstone
          port: 22
          key: ${{ secrets.GALILEO_DEPLOY }}
          script: |
            rm -r SER401-Project43
            git clone git@github.com:steven-murray/21cmSense-app.git --config core.sshCommand="ssh -i ~/.ssh/github_id_ed25519"
            cd SER401-Project43
            git pull origin master
            git status 
            ls 
