name: execute remote ssh to pull updates from master
on:
  push:
    branches:
      - master
      - dev
      - sprint10-lclindbe
  pull_request_target:
    branches:
      - dev
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: CreateDocs
        uses: cascode-labs/build-sphinx-action/action.yml@v0
        with:
          docs_path: Sphinx/source .
          conda_build_env_filepath: '{NEW_CONDA_BUILD_ENV_FILEPATH}'
          conda_build_env_name: '{NEW_CONDA_BUILD_ENV_NAME}'
          base_env_prefix: '{NEW_BASE_ENV_PREFIX}'
          artifact_name: '{NEW_ARTIFACT_NAME}'
          package_folder_path: '{NEW_PACKAGE_FOLDER_PATH}'
          package_name: '{NEW_PACKAGE_NAME}'
      - name: DeployServer
        uses:  appleboy/ssh-action@master
        with:
          host: galileo.sese.asu.edu
          username: t43-capstone
          port: 22
          key: ${{ secrets.GALILEO_DEPLOY }}
          script: |
            rm -r SER401-Project43
            git clone git@github.com:bpape1usa/SER401-Project43.git --config core.sshCommand="ssh -i ~/.ssh/github_id_ed25519"
            cd SER401-Project43
            git pull origin master
            git status 
            ls 
