name: execute remote ssh to pull updates from master
on:
  push:
    branches:
      - master
      - dev
      - github_actions_new_workflow
  pull_request_target:
    branches: 
      - master
      - dev
      - github_actions_new_workflow

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: DeployServer
        uses:  appleboy/ssh-action@master
        with:
          host: galileo.sese.asu.edu
          username: t43-capstone
          port: 22
          key: ${{ secrets.GALILEO_DEPLOY }}
          script: |
            git clone git@github.com:bpape1usa/SER401-Project43.git --config core.sshCommand="ssh -i ~/.ssh/github_id_ed25519"
            git pull origin master
            git status 
            ls 
            docker-compose up --build --remove-orphans -d
