name: execute remote ssh to pull updates from master
on:
  push:
    branches:
      - master
      - dev
      - github_actions_new_workflow
  pull_request:
    branches: 
      - master
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: bpape1usa/SER401-Project43@github_actions_new_workflow
        with:
          username: t43-capstone
          SSH_PRIVATE_KEY: ${{ secrets.GALILEO_DEPLOY }}
          REMOTE_HOST: galileo.sese.asu.edu 
          port: 22
          script: |
            ls -al
            cd /srv/shiny-server/${{ secrets.APPNAME }}
            git pull
  
