#name: Build and deploy Flask + Vue.js app to Azure App Service

on:
  push:
    branches: 
      - master
      - dev
      - github_actions_new_workflow
  pull_request:
    branches: 
      - master
      - dev

env:
  WEBAPP_NAME: 'web-app-front-end'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install and build project
      run: |
        npm install
        #npm run build # don't have build set up yet
    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install flake8 pytest pytest-cov
        pip install -r requirements.txt
    
#     - name: Lint with flake8
#       run: |
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
   
    - name: Test with pytest
      run: |
        pytest
    - name: Build Coverage File 
      run: |
        pytest --cache-clear --cov=app tests/ > pytest-coverage.txt
    - name: pytest-coverage-commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          . 
          !node_modules/
          !venv/
  
  deploy-to-webapp:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
